- defaults:
    link:
      relink: true
      create: true

- clean: ['~', '~/.config']

- create:
    - ~/.cache
    - ~/.config
    - ~/.config/bash.d
    - ~/.config/shell
    - ~/.config/zsh.d
    - ~/src

- link:
    ~/.bash_profile:
    ~/.vim:
    ~/.vimrc:

- shell:
  - git submodule sync --recursive
  - git submodule update --init --recursive
