- defaults:
    link:
      relink: true
      create: true

- shell:
  - description: Check for Github Codespaces ~/.bashrc
    quiet: true
    stderr: true
    command: |
      if [ "$CODESPACES" = true ] && [ -f ~/.bashrc ] && [ ! -f ~/codespace.bashrc ];
      then
        mv ~/.bashrc ~/codespace.bashrc
        scripts/dl-terminfo
      fi

- clean: ['~', '~/.config']

- create:
    - ~/.cache
    - ~/.config
    - ~/.local
    - ~/.local/bin
    - ~/bin
    - ~/src
    - ~/tmp
- create:
    ~/.ssh:
      mode: 0700
    ~/.ssh/config.d:
      mode: 0700

- link:
    ~/.bash_profile:
    ~/.bashrc:
    ~/.config/bash:
    ~/.config/shell:
    ~/.dotfiles: ''
    ~/.gitconfig:
    ~/.gitignore:
    ~/.vim:
    ~/.vimrc:

    ~/.terminfo/:
      if: test -d terminfo # run scripts/dl-terminfo to populate this
      glob: true
      path: terminfo/**

    ~/.ssh/config:
      path: ssh/config

- shell:
  - git submodule sync --recursive
  - git submodule update --init --recursive

  - description: Update vim helptags
    quiet: true
    stdin: true
    stderr: true
    stdout: true
    command: vim -e "+packload | helptags ALL | qall"

  - description: Install fzf
    quiet: true
    stderr: true
    stdout: true
    command: ./vim/pack/fzf/start/fzf/install --bin
