- defaults:
    link:
      relink: true
      create: true

- clean: ['~', '~/.config']

- create:
    - ~/.cache
    - ~/.config
    - ~/src

- link:
    ~/.bash_profile:
    ~/.bashrc:
    ~/.bash.d:
    ~/.vim:
    ~/.vimrc:

- shell:
  - git submodule sync --recursive
  - git submodule update --init --recursive
