---
- defaults:
    link:
      relink: true
      create: true
    shell:
      stdin: true
      stderr: true
      stdout: true

- shell:
  - description: Check for Github Codespaces ~/.bashrc
    command: bin/gh-codespace-init

- create:
  - ~/.cache
  - ~/.config
  - ~/.local
  - ~/.local/bin
  - ~/.local/share
  - ~/.local/state
  - ~/Documents
  - ~/Downloads
  - ~/bin
  - ~/src
  - ~/tmp

- create:
    ~/.ssh:
      mode: 0700
    ~/.ssh/config.d:
      mode: 0700

- clean:
  - "~"
  - "~/.config"
  - "~/.local"
  - "~/.local/bin"
  - "~/.local/share"
  - "~/.local/state"
  - "~/.ssh"

- link:
    ~/.bash_profile:
    ~/.bashrc:
    ~/.config/bash:
    ~/.config/shell:
    ~/.dotfiles: ''
    ~/.gitconfig:
    ~/.gitignore:
    ~/.profile:
    ~/.vim:
    ~/.vimrc:

    ~/.terminfo/:
      if: test -d terminfo  # run scripts/dl-terminfo to populate this
      glob: true
      path: terminfo/**

    ~/.ssh/config:
      path: ssh/config

- shell:
    - git submodule sync --recursive --quiet
    - git submodule update --init --recursive --depth 5

    - description: Update vim helptags
      quiet: true
      stdin: true
      stderr: true
      stdout: true
      command: vim -e "+packload | helptags ALL | qall"

    - description: Install fzf
      quiet: true
      stderr: true
      stdout: true
      command: |
        ./vim/pack/ui-finders/start/fzf/install \
          --xdg --completion --key-bindings --no-update-rc

    - description: Update coc.nvim
      quiet: true
      stderr: true
      command: |
        dir="vim/pack/compl_lint_lsp_etc/opt/coc.nvim"
        if [ -r "$dir"/package.json ]; then
          {
            cd "$dir"
            yarn install --frozen-lockfile
          }
        fi
